/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Test

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.routing.*
import io.ktor.http.*
import io.ktor.server.http.content.* // for serving static content
import io.ktor.server.application.*
import io.ktor.server.response.*
import io.ktor.server.request.*
import java.io.File

fun Application.configureRouting() {
    routing {
        get("/test") {
            call.respondText("Hello")
        }

        // val html = File("test.html").readText()
        // get("{...}") {
        //     call.respondText(html, ContentType.Text.Html)
        // }
    }
}

fun Route.staticContent() {
    static {
        resource("/", "test.html")
        resource("*", "test.html")
        static("static") {
            resources("static")
        }
    }
}

fun main() {
    embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
        configureRouting()
    }.start(wait = true)
}