/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Test

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {

    }
}
